Basic BCC C++ API
palmtenor/bcc pull request #2
Opened 2016-10-06 19:57 UTC by palmtenor

2016-10-06 20:14 UTC, palmtenor commented
@4ast: I don't think I'm build right correctly here. The outputted `libbcc.so` seems to be missing some GLIBC stuff and looking from symbols I don't think the newly added API files are linked in:(
Also for the examples, I think I'm supposed to link against `bcc-static` but it always fail to link because it couldn't find some symbols in `bcc_syms.cc`. Am I doing anything wrong?

2016-10-06 22:07 UTC, palmtenor commented
Everything builds and all examples run:)

2016-10-07 00:05 UTC, 4ast requested changes

2016-10-07 00:05 UTC, 4ast commented on src/cc/BPF.cc
> +      throw std::runtime_error("Unable to load probe function " + probe_func);
bcc is compiled with -fno-rtti mainly to prevent people using exceptions, since that was the agreement when we started bcc. I still have this opinion. I'd prefer explicit error checks and cleanup. Looking through the throw code I see that FD is leaking, memory is not cleaned up. I bet such errors wouldn't be there if exceptions were not used.

2016-10-07 00:05 UTC, 4ast commented on src/cc/BPF.cc
> +    bool ret_probe,
not excited about bool flag. I think attach_kprobe, attach_kretprobe are cleaner.

2016-10-07 00:05 UTC, 4ast commented on src/cc/BPF.cc
> +      throw std::runtime_error(
proper error handling should be unloading bpf prog here

2016-10-07 00:05 UTC, 4ast commented on src/cc/BPF.cc
> +  std::shared_ptr<bcc_symbol> BPF::check_binary_symbol(
please don't use shared_ptr. They're not used in bcc, because they have large memory and runtime overhead. If unique_ptr is not enough, think of different api

2016-10-07 00:05 UTC, 4ast commented on src/cc/BPFTable.h
> +  std::vector<std::pair<KeyType, ValueType>> get_table_offline() {
such 'return all entries' api is dangerous. I don't think there is ever a valid use case to do so, yet it's trivial to abuse it.

2016-10-07 00:05 UTC, 4ast commented on src/cc/BPF.cc
> +    res += std::regex_replace(kernel_func, KPROBE_EV_NAME_REPLACE, "_");
that part probably should move down to C part, since lua, python need to do the same?

2016-10-07 00:05 UTC, 4ast commented on src/cc/BPF.h
> +    perf_reader_cb cb = nullptr, void* cb_cookie = nullptr
don't see an example that shows how 'cb' is used...

2016-10-07 00:05 UTC, 4ast commented on examples/cpp/RecordCPUTime.cc
> +  auto table = bpf.get_hash_table<int, uint64_t>("cpu_time");
looks very nice

2016-10-07 00:05 UTC, 4ast commented on src/cc/BPF.h
> +class BPF {
how the whole thing fits into tcpeventd usage?

2016-10-07 01:01 UTC, palmtenor commented on src/cc/BPFTable.h
> +  std::vector<std::pair<KeyType, ValueType>> get_table_offline() {
Looking from Python tools, isn't this the most common use case? You probe things for a period of time, and then read out everything for post-processing in user space.

So in python this is done by returning a generator. Now I could probably write a C++ iterator here, but I don't think we support all the operations that an iterator would need to support.

What are the concerns and what do you have in mind?

2016-10-07 01:01 UTC, palmtenor commented on src/cc/BPF.h
> +class BPF {
Can you be most specific? I don't know too much about the tcpeventd use case.

2016-10-07 01:02 UTC, palmtenor commented on src/cc/BPF.h
> +    perf_reader_cb cb = nullptr, void* cb_cookie = nullptr
We talked about this right? You said that was some legacy behavior (return 1 for perf event listener). Should we just not keep it and always construct empty reader?

2016-10-07 01:03 UTC, palmtenor commented on src/cc/BPF.cc
> +    bool ret_probe,
Will do. That's me trying to reduce some duplicated code :D
Do you think it's better just write same code twice, or still keep a private helper method that takes boolean flag?
Would you feel better if this is an enum instead of boolean flag?

2016-10-07 01:04 UTC, palmtenor commented on src/cc/BPF.cc
> +      throw std::runtime_error("Unable to load probe function " + probe_func);
Will do exception handling and clean up all over the place. Thanks for pointing out.

2016-10-07 01:04 UTC, palmtenor commented on src/cc/BPF.cc
> +  std::shared_ptr<bcc_symbol> BPF::check_binary_symbol(
Will do.

2016-10-07 01:05 UTC, palmtenor commented on src/cc/BPF.cc
> +    res += std::regex_replace(kernel_func, KPROBE_EV_NAME_REPLACE, "_");
Yeah. I can do that.

2016-10-07 01:09 UTC, palmtenor commented on src/cc/BPF.cc
> +    res += std::regex_replace(kernel_func, KPROBE_EV_NAME_REPLACE, "_");
@4ast I think I know why this is not done in C side. The event description always look like `<TYPE PREFIX>/<EVENT_NAME> <RAW_EVENT_NAME>`, where EVENT_NAME is the formatted version but the <RAW_EVENT_NAME> is just the original string (kernel event name / binary path / etc.).

If I read correct, the event description doesn't actually matter so much. So I assume we could just to the replacement formatting for the entire thing? Or even better just construct the event description on C side?

2016-10-13 20:20 UTC, palmtenor commented
Updated according to @4ast's suggestion
- No `shared_ptr`.
- Clean up properly on exit and failure.
- Better exception handling instead of throwing out.
- Improve method argument signature.

A few questions:
- For constructor of `BPF` class (initializing the program), can we still throw exception? What would be our other options?
- I still throw for non-existent key lookup, is that OK?
- What's the concern for "return all entries" operation? I thought it's very useful for probe-the-post-processing model.
- Will try handle the event formatting in a separated change.

2016-11-29 05:46 UTC, merged